Project search filtering
TAP-GGC/tap-ws1-astro-agnosticui pull request #1
Opened 2024-02-06 02:29 UTC by Farce4wrd

-Implemented filtering by dropdown (Tech, Level, Difficulty, Duration, and Semester)
-Implemented filtering through search input in conjunction

2024-02-07 16:26 UTC, cengique requested changes
Minor changes requested and some pending questions.

2024-02-07 16:26 UTC, cengique commented on src/content/test/mytest.md
> +---
@Farce4wrd do we need this file?

2024-02-07 16:26 UTC, cengique commented on src/components/ProjectSearch.vue
> +                    :options="semesterList" :is-multiple="true" :multiple-size="3"></Select>
@Farce4wrd let's make all of them multi-select

2024-02-07 16:26 UTC, cengique commented on src/components/ProjectSearch.vue
> +const levelOptions = computed(() => createOptions("levels") );
Nice and clean

2024-02-07 16:26 UTC, cengique commented on src/components/TAPHeader.vue
> +        <HeaderNavItem>
Did we need this?

2024-02-07 16:34 UTC, Farce4wrd commented on src/content/test/mytest.md
> +---
Oops! I had that when I was trying to learn and understand ASTRO. Nope, it'll have to go

2024-02-07 16:35 UTC, Farce4wrd commented on src/components/TAPHeader.vue
> +        <HeaderNavItem>
I assume this is related to the test.md. I'll remove it

2024-02-18 22:04 UTC, cengique approved these changes

2024-02-18 22:05 UTC, merged