New branch MDX2
TAP-GGC/tap-ws1-astro-agnosticui pull request #28
Opened 2024-06-17 03:52 UTC by trungddao

- copied the works of MDX
- make changes: display alt for logo, change heading back to ##

2024-06-28 08:43 UTC, cengique requested changes
MDX files look good overall

2024-06-28 08:43 UTC, cengique commented on src/content/projects/2023-01Spring/Foe/Foe.mdx
> +#### From left to right:  Alec Burns, Alex Shaklee
shouldn't this go into the caption?

2024-06-28 08:43 UTC, cengique commented on src/content/projects/2023-08Fall/jedi/Jedi.mdx
> +    { src: 'jedi/JediImage.jpg', alt:'Jedi at S3 photo', link: 'jedi/JediImage.jpg' },
why do we need both src and link? Aren't they the same?

2024-06-28 08:43 UTC, cengique commented on src/content/projects/2023-08Fall/jedi/Jedi.mdx
> +    { src: 'jedi/JediImage.jpg', alt:'Jedi at S3 photo', link: 'jedi/JediImage.jpg' },
Maybe we can check and if link is not provided, src is reused.

2024-06-28 08:43 UTC, cengique commented on src/content/projects/2023-08Fall/jedi/Jedi.mdx
> +`on start program`<br />
for code sections, you can use the `<pre>` tag and then you won't need `<br>`s

2024-06-28 08:43 UTC, cengique commented on src/content/projects/2023-08Fall/jedi/Jedi.mdx
> +<div style='text-align:center; float: right; margin-left: 205px; vertical-align: bottom; display: inline-block;font-size: 1.125em;'>
these are still looking awkward and not side-by-side for me.

2024-06-28 08:43 UTC, cengique commented on src/content/projects/2023-08Fall/monsterMakey/monsterMakey.mdx
> +<Logo src= {scratchImage.src} alt="Scratch Sample" />
link to scratch website?

2024-06-28 08:43 UTC, cengique commented on src/content/projects/2024-01Spring/NinjaTurtles/ninjaturtles.mdx
> +<Logo src={scratchlogo.src} alt="Scratch Logo"/>
link to scratch website; no need to call it "Scratch Logo"

2024-06-28 08:43 UTC, cengique commented on src/content/projects/2024-01Spring/blendingReality/blendingReality.mdx
> +- [Download Blender & Aero(Desktop & Mobile) - PDF](https://github.com/TAP-GGC/QuantumQuirks/blob/main/Documents/How%20download%20Blender%20and%20Aero.pdf)
Isn't this the Adobe Aero logo? Maybe link them to the websites. Also we may not need both.

2024-06-28 08:43 UTC, cengique commented on src/content/projects/2024-01Spring/blendingReality/blendingReality.mdx
> +- [Building a Snowman in Blender](https://youtu.be/NL7IVITbNt0?si=NV3Kq1guVl0LHK-f)
we should use the iframe for this video

2024-07-02 04:33 UTC, trungddao commented on src/content/projects/2023-08Fall/jedi/Jedi.mdx
> +    { src: 'jedi/JediImage.jpg', alt:'Jedi at S3 photo', link: 'jedi/JediImage.jpg' },
This gallery attempts to run Light Gallery, but the images are not working for me yet. Maybe when we can get Light Gallery work i can look into that

2024-07-02 04:38 UTC, trungddao commented on src/content/projects/2024-01Spring/blendingReality/blendingReality.mdx
> +- [Building a Snowman in Blender](https://youtu.be/NL7IVITbNt0?si=NV3Kq1guVl0LHK-f)
i don't know if we should use full screen, which is better on the eyes but make the section look rather disconnected, mean while, making them fit the section look funny, maybe meet in the middle and make it half full page?

![Screenshot 2024-07-02 at 00 30 12](https://github.com/TAP-GGC/tap-ws1-astro-agnosticui/assets/142435978/3d9be01a-af07-4fd3-9117-84193b0702a7)
![Screenshot 2024-07-02 at 00 26 14](https://github.com/TAP-GGC/tap-ws1-astro-agnosticui/assets/142435978/a87d4c06-d7e5-4ece-9994-cb0f144d471f)

2024-07-02 04:38 UTC, trungddao commented on src/content/projects/2023-08Fall/jedi/Jedi.mdx
> +<div style='text-align:center; float: right; margin-left: 205px; vertical-align: bottom; display: inline-block;font-size: 1.125em;'>
Same as above, i think we should get rid of it

2024-07-02 04:38 UTC, trungddao commented on src/content/projects/2023-08Fall/jedi/Jedi.mdx
> +`on start program`<br />
I think we should get rid of these sections altogether because it is going in-depth on how to run the code with a program on a tablet, and showing them early isn't really necessary

2024-07-02 04:44 UTC, trungddao commented on src/content/projects/2023-01Spring/Foe/Foe.mdx
> +#### From left to right:  Alec Burns, Alex Shaklee
The photo looks better full screen so I keep it as Image and not Photo since the photo has a smaller dimension to fit the gallery. But I can modify the Photo.astro component to give them full size since the gallery div gave them dimension already?

2024-07-02 04:54 UTC, trungddao commented on src/content/projects/2023-08Fall/jedi/Jedi.mdx
> +    { src: 'jedi/JediImage.jpg', alt:'Jedi at S3 photo', link: 'jedi/JediImage.jpg' },
LightGallery does not update slides by default so we should look into that?

2024-07-03 14:05 UTC, cengique commented on src/content/projects/2024-01Spring/blendingReality/blendingReality.mdx
> +- [Building a Snowman in Blender](https://youtu.be/NL7IVITbNt0?si=NV3Kq1guVl0LHK-f)
ok, half-page is fine!

2024-07-13 21:02 UTC, cengique approved these changes
@trungddao gallery css looks great!

2024-07-14 21:40 UTC, cengique approved these changes

2024-07-15 05:28 UTC, merged