Adding new search page
TAP-GGC/tap-ws1-astro-agnosticui pull request #34
Opened 2024-08-24 05:51 UTC by trungddao

- Add curator for meta data
- Make students and advisor clickable
- first attemp for [projectStudents].astro
- Make first look on techs.astro landing page

2024-08-24 05:55 UTC, trungddao commented on src/pages/students/[...projectStudent].astro
IDK what to lead when clicking on student, maybe their portfolio website, LinkedIn, GitHub?

2024-08-24 22:31 UTC, cengique commented on src/pages/students/[...projectStudent].astro
We need to create a new content collection for students and faculty, have their own metadata, and show a simple profile page for them. Below the profile, we can list the projectSearch results for the projects they were involved in as curator/student. We can discuss about this.

2024-08-24 22:34 UTC, cengique requested changes

2024-08-24 22:34 UTC, cengique commented on src/pages/techs.astro
> +---
I like what you have so far. You can display the information in a table format with tech in first column and number of projects in second. https://www.agnosticui.com/docs/components/table.html

2024-09-08 21:25 UTC, cengique approved these changes
approving tech table

2024-09-08 21:25 UTC, merged