Crumbs
TAP-GGC/tap-ws1-astro-agnosticui pull request #4
Opened 2024-02-24 18:29 UTC by CEOHurdleHopper

I believe the crumbs are completed, and I just want to have this breadcrumb code reviewed to see if I can move on to the next task.

2024-02-24 22:14 UTC, cengique requested changes
@CEOHurdleHopper overall great job! But clean up the cruft as I marked and I'll do another review.

2024-02-24 22:14 UTC, cengique commented on package.json
> +    "vue-router": "^4.2.5"
@CEOHurdleHopper is this necessary? Otherwise, remove.

2024-02-24 22:14 UTC, cengique commented on src/components/BreadCrumbs.astro
> +---
You need to merge this code into the Crumbs.vue. We don't need two files for this.

2024-02-24 22:14 UTC, cengique commented on src/components/BreadCrumbs.astro
> +const homePage = "http://localhost:4321/"
if these are not used, remove. You can't hard-code localhost as it won't work in deployment.

2024-02-24 22:14 UTC, cengique commented on src/components/Crumbs.vue
> +if(pageProp.pageType == "project"){
else if

2024-02-24 22:14 UTC, cengique commented on src/components/BreadCrumbs.astro
> +---
Is this file even used?

2024-02-24 22:14 UTC, cengique commented on src/pages/index.astro
> +//import of custom bread-crumb component
delete

2024-02-24 22:14 UTC, cengique commented on src/pages/index.astro
> +		<!--Because "TAPHeader" is a Vue.js3 component it can be called with the client:load applied to it the "Heading" which is a Astro component cannot -->
delete

2024-02-24 22:14 UTC, cengique commented on src/pages/posts/[...slug].astro
> +		<Crumbs pageType="post" pageUrl=`/posts/${postTag}/${postName}` client:load/>
if this is here, why is it not implemented?

2024-02-24 22:14 UTC, cengique commented on src/components/TAPHeader.vue
> +          <!-- edited the href call so that this nav object pointed to the proper url -->
put comments in commit messages rather than code. delete

2024-02-24 22:14 UTC, cengique commented on src/components/TAPHeader.vue
> +            <!--need to add appropriate href for the join section-->
delete

2024-02-24 22:14 UTC, cengique commented on src/pages/projects.astro
> +    <Crumbs pageType="projects" pageUrl="/Projects" client:load/>
why do you need client:load? this is not a dynamic component

2024-02-24 22:14 UTC, cengique commented on src/pages/projects/[...slug].astro
> +		<Crumbs pageType="project" pageUrl=`/projects/${projYear}/${projSemester}/${projName}` client:load/>
remove client:load if unnecessary

2024-02-24 22:14 UTC, cengique commented on src/pages/posts/[...slug].astro
> +		<Crumbs pageType="post" pageUrl=`/posts/${postTag}/${postName}` client:load/>
also remove client:load

2024-02-25 21:36 UTC, CEOHurdleHopper reviewed
I completed the review of what you had commented on Dr. Gunay.

2024-02-25 21:36 UTC, CEOHurdleHopper commented on src/pages/posts/[...slug].astro
> +		<Crumbs pageType="post" pageUrl=`/posts/${postTag}/${postName}` client:load/>
I only didn't implement these because the post page is not ready yet, but I will implement their part in the Crumbs.vue component.

2024-02-25 21:36 UTC, CEOHurdleHopper commented on src/pages/projects/[...slug].astro
> +		<Crumbs pageType="project" pageUrl=`/projects/${projYear}/${projSemester}/${projName}` client:load/>
I found the client:load to actually be unnecessary, but is this because the crumb is already known before the page is fully created?

2024-02-25 22:09 UTC, cengique commented on src/pages/posts/[...slug].astro
> +		<Crumbs pageType="post" pageUrl=`/posts/${postTag}/${postName}` />
This will be changed once we fix the posts, but we can leave it as a placeholder.

2024-02-25 22:09 UTC, cengique commented on src/pages/projects/[...slug].astro
> +		<Crumbs pageType="project" pageUrl=`/projects/${projYear}/${projSemester}/${projName}` client:load/>
@CEOHurdleHopper client:load is only necessary when the Javascript is needed after the page is created. In this instance, we use Javascript to create the crumbs component, but after that there is no dynamic component - it's just an href.

2024-02-25 22:10 UTC, cengique approved these changes
All good, thanks for fixing all!

2024-02-25 22:16 UTC, merged