Adding first project jedi
TAP-GGC/tap-ws1-astro-agnosticui pull request #5
Opened 2024-03-07 03:26 UTC by CEOHurdleHopper

Added the first real project "Jedi" to the TAP website with appropriate links, details, and an image.

2024-03-07 17:01 UTC, cengique requested changes
@CEOHurdleHopper this is a great start and it's good to see the website flesh out with its first project! You have the major pieces in place, but I need a lot of changes. Let me know if you need clarifications.

2024-03-08 17:20 UTC, CEOHurdleHopper commented on src/components/Crumbs.Vue
> +
@cengique I think I forgot to delete the Crumbs file before creating this new branch. I'll make sure to create future branches from main, and also keep them up to date as new changes arise during development.

2024-03-08 17:31 UTC, CEOHurdleHopper commented on src/content/config.ts
> +    image:image().refine((img) => img.width >= 10, {
@cengique I will make the comment now.

2024-03-08 17:35 UTC, CEOHurdleHopper commented on src/components/Crumbs.Vue
> +
@cengique I believe that I forgot to delete this old Crumbs component before creating this Jedi branch from my previous Crumbs branch. I will make sure to create branches from main, and keep up with any changes that arise during the development process.

2024-03-08 17:38 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +image: ./JediImage.jpg
@cengique Thank you, when the new square image is available please let me know and I will add the proper image to the Jedi directory.

2024-03-08 17:44 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +desc: The primary goal of this project is educating others about algorithms by programming a robot through a maze using SpheroEDU. Sphero is a small robot ball that moves around by either remote cont
@cengique I reduced the description size down to one line.

2024-03-08 17:48 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +id: P-0001
@cengique made the title of the project more specific to the actual project by using the name you suggested.

2024-03-08 18:01 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +techs: [Sphero]
@cengique Completed this task.

2024-03-08 18:03 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +tags: [ Sphero, STEM, TAP]
@cengique Left the tags section empty for now.

2024-03-08 18:10 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +videos: []
@cengique I added the url to the videos slug section.

2024-03-08 18:12 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +levels: [ 6th-12th, college ]
@cengique I edited these to make them more simple.

2024-03-08 18:15 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +publishedDate: 2023-11-05
@cengique I added todays date.

2024-03-08 18:16 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +The primary goal of this project is educating others about algorithms by programming a robot through a maze using SpheroEDU. Sphero is a small robot ball that moves around by either remote control or
@cengique I will remember this for future project descriptions.

2024-03-08 18:39 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +id: P-0001
@cengique also changed the id so that the title and the url matched.

2024-03-08 18:41 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +github: https://github.com/TAP-GGC/Jedi?tab=readme-ov-file
@cengique I cleared out all the question comments

2024-03-08 18:42 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +events: [ CCSC-2023, S3-Fall-2023, TAP Expo-Fall-2023]
@cengique After carful review I realize that only one of these are accurate that being the TAP Expo one.

2024-03-08 18:51 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +durationMins: [ 60, 90 ]
@cengique This is all accurate I got this information from the "description" section on the GitHub page.

2024-03-08 18:53 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +</br>
@cengique I believe that I took away all unnecessary HTML.

2024-03-19 20:16 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +- Create a SpheroEDU teacher account.
I have added the CSS for styling the bullets and a unique name for that styling, but for the pdf files located in the projects documentation section on Github I was unable to figure out how to create pdf links for them. Assistance with this would be very helpful.

2024-03-19 21:09 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +<a href="https://youtu.be/W7AJaQqIAE0"> Demo Instructions </a>
I moved up the video and also changed it to a Markdown syntax call, but when you ask me to get everything from the repo do you mean the Readme or the entire repo? @cengique

2024-03-19 21:11 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +## Full Project Page:
This has been changed to the correct descriptive title of "GitHub Source Code".

2024-03-19 21:14 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +<div id="images">
I created a CSS definition at the bottom of the jedi.md file. I also added a descriptive title for the images div.

2024-03-25 02:32 UTC, cengique approved these changes
Merging pull request, but you need to come back here for the comments and keep working on it @CEOHurdleHopper

2024-03-25 02:32 UTC, cengique commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +<a href="https://youtu.be/W7AJaQqIAE0"> Demo Instructions </a>
I added the video using iframe embed

2024-03-25 02:32 UTC, cengique commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +- Create a SpheroEDU teacher account.
fixed it

2024-03-25 02:32 UTC, cengique commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +- Create a SpheroEDU teacher account.
added an example PDF link to Github. The answer is you need all the stuff from the README replicated here.

2024-03-25 02:32 UTC, merged

2024-03-25 18:24 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +- Create a SpheroEDU teacher account.
I just realized that I had not pushed my changes to the branch and that is why they did not show up. Also thank you @cengique for helping me with this I will make sure to push my changes like I did at the beginning of this PR review.