Adding first project jedi
TAP-GGC/tap-ws1-astro-agnosticui pull request #8
Opened 2024-03-28 18:11 UTC by CEOHurdleHopper

Added more links, pdfs, and some styling for the Jedi project page.

2024-03-29 00:45 UTC, cengique requested changes
It looks better! Just fix that one change and we can merge it in.

2024-03-29 00:45 UTC, cengique commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +**The primary goal of this project is educating others about algorithms by programming a robot through a maze using SpheroEDU. Sphero is a small robot ball that moves around by either remote control
@CEOHurdleHopper I wouldn't make the whole paragraph bold.

2024-03-29 15:32 UTC, CEOHurdleHopper commented on src/content/projects/2023-08Fall/jedi/Jedi.md
> +**The primary goal of this project is educating others about algorithms by programming a robot through a maze using SpheroEDU. Sphero is a small robot ball that moves around by either remote control
@cengique That should be easy enough to fix.

2024-04-03 00:17 UTC, cengique approved these changes

2024-04-03 00:17 UTC, merged